export interface LinuxNetworkIntf {
  "br0_addresses": Array<string>,
  "br0_gateway": string,
  "br0_nameservers": Array<string>,
  "eth0_mac": string,
  "eth0_dhcp": boolean,
  "eth0_addresses": Array<string>,
  "eth0_gateway": string,
  "eth0_nameservers": Array<string>,
  "eth1_mac": string,
  "eth1_dhcp": boolean,
  "eth1_addresses": Array<string>,
  "eth1_gateway": string,
  "eth1_nameservers": Array<string>,
  "wifi_addresses": Array<string>,
  "wifi_gateway": string,
  "wifi_nameservers": Array<string>,
  "wifi_ssid": string,
  "wifi_ssid_password": string,
};
